// Quote categories supported by DayStart
export type QuoteCategory =
  | 'buddhist'
  | 'christian'
  | 'goodFeelings'
  | 'hindu'
  | 'inspirational'
  | 'jewish'
  | 'mindfulness'
  | 'muslim'
  | 'philosophical'
  | 'stoic'
  | 'success'
  | 'zen';

// Canonical quote library. Each entry should be a single string in the form
// "Quote text — Attribution" or "Quote text - Attribution".
export const quoteLibrary: Record<QuoteCategory, string[]> = {
  buddhist: [
    "All that we are is the result of what we have thought. - Dhammapada",
    "Hatred is never appeased by hatred; by non-hatred alone is hatred appeased. - Dhammapada",
    "Better than a thousand hollow words is one word that brings peace. - Dhammapada",
    "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship. - Dhammapada",
    "As a solid rock is not shaken by the wind, so the wise are not moved by praise or blame. - Dhammapada",
    "With our thoughts we make the world. - Dhammapada",
    "To understand everything is to forgive everything. - Buddha",
    "No one saves us but ourselves. We must walk the path. - Buddha",
    "Peace comes from within. Do not seek it without. - Buddha",
    "A jug fills drop by drop. - Dhammapada",
    "Three things cannot be long hidden: the sun, the moon, and the truth. - Buddha",
    "If anything is worth doing, do it with all your heart. - Dhammapada",
    "There is no fear for one whose mind is not filled with desires. - Dhammapada",
    "The root of suffering is attachment. - Buddha",
    "If we fail to look deeply, we will be carried away by appearances. - Thich Nhat Hanh",
    "Smile, breathe, and go slowly. - Thich Nhat Hanh",
    "Drink your tea slowly and reverently, as if it is the axis on which the world earth revolves. - Thich Nhat Hanh",
    "Because you are alive, everything is possible. - Thich Nhat Hanh",
    "The present moment is the only moment available to us. - Thich Nhat Hanh",
    "My religion is kindness. - Dalai Lama",
    "Sleep is the best meditation. - Dalai Lama",
    "Be kind whenever possible. It is always possible. - Dalai Lama",
    "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
    "Choose to be optimistic; it feels better. - Dalai Lama",
    "If your compassion does not include yourself, it is incomplete. - Jack Kornfield",
    "The trouble is, you think you have time. - Buddha",
    "Do not dwell in the past; do not dream of the future; concentrate the mind on the present moment. - Buddha",
    "An idea that is developed and put into action is more important than an idea that exists only as an idea. - Buddha",
    "To keep the body in good health is a duty; otherwise we shall not be able to keep our mind strong and clear. - Buddha",
    "Give, even if you only have a little. - Dhammapada",
    "Should a seeker do good, let them do it again and again; the mind delights in goodness. - Dhammapada",
    "As rain does not break through a well-thatched house, passion does not break through a well-trained mind. - Dhammapada",
    "Whatever is not yours, let it go; your letting go will be for your long-term happiness and benefit. - Alagaddupama Sutta",
    "What you think, you become; what you feel, you attract; what you imagine, you create. - Buddha",
    "If you truly loved yourself, you could never hurt another. - Buddha",
    "Let go of what has passed. Let go of what may come. Be here now. - Buddha",
    "Purity and impurity depend on oneself; no one can purify another. - Dhammapada",
    "Those who are awake live in a state of constant amazement. - Buddha",
    "Be a lamp unto yourself. - Buddha",
    "Patience is the highest ascetic practice. - Dhammapada",
    "To conquer oneself is a greater task than conquering others. - Dhammapada",
    "As a candle cannot burn without fire, humans cannot live without a spiritual life. - Buddha",
    "If the problem can be solved, why worry? If it cannot be solved, worrying will do you no good. - Shantideva",
    "Wherever you are, be there totally. - Thich Nhat Hanh",
    "When the mind is clear, joy follows like a never-ending shadow. - Dhammapada",
    "From a withered tree, a flower blooms. - Zen saying",
    "When you realize how perfect everything is, you will tilt your head back and laugh at the sky. - Buddha",
    "Meditation brings wisdom; lack of meditation leaves ignorance. - Dhammapada",
    "Arise. Do not be negligent. Live the Dhamma well. - Dhammapada",
    "Your work is to discover your work and then with all your heart to give yourself to it. - Buddha"
  ],
  christian: [
    "This is the day the LORD has made; let us rejoice and be glad in it. - Psalm 118:24 (NIV)",
    "Trust in the LORD with all your heart and lean not on your own understanding. - Proverbs 3:5 (NIV)",
    "In all your ways submit to him, and he will make your paths straight. - Proverbs 3:6 (NIV)",
    "Be still, and know that I am God. - Psalm 46:10 (NIV)",
    "I can do all this through him who gives me strength. - Philippians 4:13 (NIV)",
    "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. - Philippians 4:6 (NIV)",
    "But seek first his kingdom and his righteousness, and all these things will be given to you as well. - Matthew 6:33 (NIV)",
    "But those who hope in the LORD will renew their strength. They will soar on wings like eagles. - Isaiah 40:31 (NIV)",
    "Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged, for the LORD your God will be with you wherever you go. - Joshua 1:9 (NIV)",
    "Take delight in the LORD, and he will give you the desires of your heart. - Psalm 37:4 (NIV)",
    "Commit your way to the LORD; trust in him and he will do this. - Psalm 37:5 (NIV)",
    "Cast your cares on the LORD and he will sustain you; he will never let the righteous be shaken. - Psalm 55:22 (NIV)",
    "Taste and see that the LORD is good; blessed is the one who takes refuge in him. - Psalm 34:8 (NIV)",
    "The LORD is close to the brokenhearted and saves those who are crushed in spirit. - Psalm 34:18 (NIV)",
    "Come to me, all you who are weary and burdened, and I will give you rest. - Matthew 11:28 (NIV)",
    "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline. - 2 Timothy 1:7 (NIV)",
    "Do not be overcome by evil, but overcome evil with good. - Romans 12:21 (NIV)",
    "If God is for us, who can be against us? - Romans 8:31 (NIV)",
    "And we know that in all things God works for the good of those who love him, who have been called according to his purpose. - Romans 8:28 (NIV)",
    "I lift up my eyes to the mountains—where does my help come from? My help comes from the LORD, the Maker of heaven and earth. - Psalm 121:1-2 (NIV)",
    "May these words of my mouth and this meditation of my heart be pleasing in your sight, LORD, my Rock and my Redeemer. - Psalm 19:14 (NIV)",
    "Commit to the LORD whatever you do, and he will establish your plans. - Proverbs 16:3 (NIV)",
    "In their hearts humans plan their course, but the LORD establishes their steps. - Proverbs 16:9 (NIV)",
    "Above all else, guard your heart, for everything you do flows from it. - Proverbs 4:23 (NIV)",
    "If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault, and it will be given to you. - James 1:5 (NIV)",
    "Blessed is the one who perseveres under trial. - James 1:12 (NIV)",
    "Every good and perfect gift is from above, coming down from the Father of the heavenly lights. - James 1:17 (NIV)",
    "Come near to God and he will come near to you. - James 4:8 (NIV)",
    "Blessed are the peacemakers, for they will be called children of God. - Matthew 5:9 (NIV)",
    "Let your light shine before others, that they may see your good deeds and glorify your Father in heaven. - Matthew 5:16 (NIV)",
    "Ask and it will be given to you; seek and you will find; knock and the door will be opened to you. - Matthew 7:7 (NIV)",
    "Therefore do not worry about tomorrow. - Matthew 6:34 (NIV)",
    "For where your treasure is, there your heart will be also. - Matthew 6:21 (NIV)",
    "Peace I leave with you; my peace I give you. - John 14:27 (NIV)",
    "In this world you will have trouble. But take heart! I have overcome the world. - John 16:33 (NIV)",
    "Teach us to number our days, that we may gain a heart of wisdom. - Psalm 90:12 (NIV)",
    "They will have no fear of bad news; their hearts are steadfast, trusting in the LORD. - Psalm 112:7 (NIV)",
    "Your word is a lamp for my feet, a light on my path. - Psalm 119:105 (NIV)",
    "Do not boast about tomorrow, for you do not know what a day may bring. - Proverbs 27:1 (NIV)",
    "Because of the LORD’s great love we are not consumed, for his compassions never fail. They are new every morning. - Lamentations 3:22-23 (NIV)",
    "Whatever you do, work at it with all your heart, as working for the Lord, not for human masters. - Colossians 3:23 (NIV)",
    "Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you. - Ephesians 4:32 (NIV)",
    "Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up. - Galatians 6:9 (NIV)",
    "Let us run with perseverance the race marked out for us. - Hebrews 12:1 (NIV)",
    "Never will I leave you; never will I forsake you. - Hebrews 13:5 (NIV)",
    "Praise the LORD, my soul, and forget not all his benefits. - Psalm 103:2 (NIV)",
    "I keep my eyes always on the LORD. With him at my right hand, I will not be shaken. - Psalm 16:8 (NIV)",
    "It is God who arms me with strength and keeps my way secure. - Psalm 18:32 (NIV)",
    "You will keep in perfect peace those whose minds are steadfast, because they trust in you. - Isaiah 26:3 (NIV)",
    "So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand. - Isaiah 41:10 (NIV)"
  ],
  goodFeelings: [
    "Wherever you go, no matter what the weather, always bring your own sunshine. - Anthony J. D'Angelo",
    "Happiness is not by chance, but by choice. - Jim Rohn",
    "If you want to be happy, be. - Leo Tolstoy",
    "The most wasted of all days is one without laughter. - Nicolas Chamfort",
    "Joy is not in things; it is in us. - Richard Wagner",
    "Try to be a rainbow in someone else's cloud. - Maya Angelou",
    "A day without laughter is a day wasted. - Charlie Chaplin",
    "Let us be grateful to people who make us happy; they are the charming gardeners who make our souls blossom. - Marcel Proust",
    "Keep smiling, because life is a beautiful thing and there's so much to smile about. - Marilyn Monroe",
    "The earth laughs in flowers. - Ralph Waldo Emerson",
    "Count your age by friends, not years. Count your life by smiles, not tears. - John Lennon",
    "A warm smile is the universal language of kindness. - William Arthur Ward",
    "Happiness is a direction, not a place. - Sydney J. Harris",
    "The miracle is this: the more we share, the more we have. - Leonard Nimoy",
    "The best way to cheer yourself is to try to cheer someone else up. - Mark Twain",
    "Nothing can dim the light which shines from within. - Maya Angelou",
    "We can complain because rose bushes have thorns, or rejoice because thorn bushes have roses. - Alphonse Karr",
    "Live in the sunshine, swim the sea, drink the wild air. - Ralph Waldo Emerson",
    "Happiness is a warm puppy. - Charles M. Schulz",
    "Gratitude turns what we have into enough. - Aesop",
    "Wherever there is a human being, there is an opportunity for kindness. - Seneca",
    "Some people look for a beautiful place. Others make a place beautiful. - Hazrat Inayat Khan",
    "The purpose of our lives is to be happy. - Dalai Lama",
    "The more you praise and celebrate your life, the more there is in life to celebrate. - Oprah Winfrey",
    "Keep a green tree in your heart and perhaps a singing bird will come. - Chinese Proverb",
    "A good laugh is sunshine in the house. - William Makepeace Thackeray",
    "Joy does not simply happen to us. We have to choose joy and keep choosing it every day. - Henri Nouwen",
    "Let your smile change the world; don't let the world change your smile. - Unknown",
    "Happiness is a habit—cultivate it. - Elbert Hubbard",
    "Find ecstasy in life; the mere sense of living is joy enough. - Emily Dickinson",
    "Where there is love there is life. - Mahatma Gandhi",
    "We are all in the gutter, but some of us are looking at the stars. - Oscar Wilde",
    "Joy is the simplest form of gratitude. - Karl Barth",
    "Do more of what makes you happy. - Unknown",
    "Let your joy be in your journey, not in some distant goal. - Tim Cook",
    "If you want to be happy, set a goal that commands your thoughts, liberates your energy, and inspires your hopes. - Andrew Carnegie",
    "Wear a smile and have friends; wear a scowl and have wrinkles. - George Eliot",
    "Be yourself; everyone else is already taken. - Oscar Wilde",
    "A smile is happiness you'll find right under your nose. - Tom Wilson",
    "There is joy in work. There is no happiness except in the realization that we have accomplished something. - Henry Ford",
    "Happiness often sneaks in through a door you didn't know you left open. - John Barrymore",
    "The more light you allow within you, the brighter the world you live in will be. - Shakti Gawain",
    "Happiness is not something you postpone for the future; it is something you design for the present. - Jim Rohn",
    "Let us live so that when we come to die even the undertaker will be sorry. - Mark Twain",
    "Where there is hope, there is joy. - George Iles",
    "Scatter joy. - Ralph Waldo Emerson",
    "A joyful heart makes a cheerful face. - Proverbs 15:13",
    "There are always flowers for those who want to see them. - Henri Matisse",
    "The present moment is filled with joy and happiness. If you are attentive, you will see it. - Thich Nhat Hanh"
  ],
  hindu: [
    "You have the right to work, but not to the fruits of work. - Bhagavad Gita 2:47",
    "Yoga is skill in action. - Bhagavad Gita 2:50",
    "Perform action without attachment; be steadfast in success and failure. - Bhagavad Gita 2:48",
    "Better to do one's own duty imperfectly than another's perfectly. - Bhagavad Gita 3:35",
    "Work must be done as sacrifice; otherwise work binds. - Bhagavad Gita 3:9",
    "Let a man lift himself by himself; let him not degrade himself. - Bhagavad Gita 6:5",
    "For one who has conquered the mind, it is the best of friends. - Bhagavad Gita 6:6",
    "As a lamp in a windless place does not flicker, so is the yogi's mind. - Bhagavad Gita 6:19",
    "From whatever cause the mind wanders, let him bring it back under the control of the Self. - Bhagavad Gita 6:26",
    "By practice and by detachment the mind is restrained. - Bhagavad Gita 6:35",
    "He who sees inaction in action and action in inaction is wise. - Bhagavad Gita 4:18",
    "In this world there is nothing so purifying as knowledge. - Bhagavad Gita 4:38",
    "When goodness grows weak and unrighteousness prevails, I manifest. - Bhagavad Gita 4:7",
    "Abandoning attachment, perform action as duty. - Bhagavad Gita 3:19",
    "Whoever is content with what comes by chance, who has passed beyond dualities, is free. - Bhagavad Gita 4:22",
    "He whose mind is steady gains peace. - Bhagavad Gita 2:64",
    "When a man is devoted to his own duty, he soon attains perfection. - Bhagavad Gita 18:45",
    "Whatever you do, whatever you eat, whatever you offer—do that as an offering. - Bhagavad Gita 9:27",
    "One becomes what one's deep, driving desire is. - Brihadaranyaka Upanishad",
    "The Self is not born, nor does it die. - Katha Upanishad",
    "Arise! Awake! and stop not till the goal is reached. - Katha Upanishad",
    "From the unreal lead me to the real; from darkness to light; from death to immortality. - Brihadaranyaka Upanishad",
    "That thou art. - Chandogya Upanishad",
    "When the senses are stilled and the mind is at rest, then begins the highest path. - Katha Upanishad",
    "This Self cannot be won by the weak. - Katha Upanishad",
    "He sees all beings in the Self and the Self in all beings; he does not shrink from it. - Isha Upanishad",
    "As is a man's will, so is his deed; as is his deed, so is his destiny. - Brihadaranyaka Upanishad",
    "All power is within you; you can do anything and everything. - Swami Vivekananda",
    "Take up one idea. Make that one idea your life. - Swami Vivekananda",
    "Strength is life; weakness is death. - Swami Vivekananda",
    "You cannot believe in God until you believe in yourself. - Swami Vivekananda",
    "Perform every action with your heart fixed on the Supreme. - Bhagavad Gita 3:30",
    "He who is free from malice toward all beings, friendly and compassionate, is dear to Me. - Bhagavad Gita 12:13",
    "Better indeed is knowledge than practice; meditation excels knowledge. - Bhagavad Gita 12:12",
    "The yogi who is disciplined in mind attains peace. - Bhagavad Gita 6:15",
    "He who is not disturbed by happiness and distress is fit for immortality. - Bhagavad Gita 2:15",
    "A gift is pure when given from the heart at the right time and place. - Bhagavad Gita 17:20",
    "The person who is not motivated by the fruits of work is the true renunciate. - Bhagavad Gita 6:1",
    "When he has let go of all desires, he finds peace. - Bhagavad Gita 2:71",
    "To love and to work without attachment is freedom. - Bhagavad Gita (teaching summarized)",
    "By selfless service, one attains the highest. - Bhagavad Gita 3:20",
    "He who sees Me everywhere and sees everything in Me, I am never lost to him. - Bhagavad Gita 6:30",
    "For those who are resolute in purpose, the intelligence is one-pointed. - Bhagavad Gita 2:41",
    "As a person sheds worn-out garments and wears new ones, so the Self discards worn-out bodies. - Bhagavad Gita 2:22",
    "To the disciplined, happiness springs from within. - Bhagavad Gita 5:24",
    "Let your acts be worship. - Bhagavad Gita 3:9",
    "Peace comes to the one who abandons all desires and moves without longing. - Bhagavad Gita 2:71",
    "When meditation is mastered, the mind is unwavering like a lamp in a windless place. - Bhagavad Gita 6:19"
  ],
  inspirational: [
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
    "It is never too late to be what you might have been. - George Eliot",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
    "We are what we repeatedly do. Excellence, then, is not an act but a habit. - Will Durant",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "Everything you can imagine is real. - Pablo Picasso",
    "The future belongs to those who prepare for it today. - Malcolm X",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Fall seven times and stand up eight. - Japanese Proverb",
    "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
    "In the middle of difficulty lies opportunity. - Albert Einstein",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
    "Act as if what you do makes a difference. It does. - William James",
    "Happiness depends upon ourselves. - Aristotle",
    "You are never too old to set another goal or to dream a new dream. - C. S. Lewis",
    "Small deeds done are better than great deeds planned. - Peter Marshall",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "The journey of a thousand miles begins with one step. - Lao Tzu",
    "If you're going through hell, keep going. - Winston Churchill",
    "Nothing will work unless you do. - Maya Angelou",
    "Courage is grace under pressure. - Ernest Hemingway",
    "What we achieve inwardly will change outer reality. - Plutarch",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "Dream big. Start small. Act now. - Robin Sharma",
    "You become what you believe. - Oprah Winfrey",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "Your life does not get better by chance, it gets better by change. - Jim Rohn",
    "The best way out is always through. - Robert Frost",
    "What you do today can improve all your tomorrows. - Ralph Marston",
    "Every morning we are born again. What we do today matters most. - Attributed to Buddha",
    "The sun himself is weak when he first rises, and gathers strength and courage as the day gets on. - Charles Dickens",
    "Perseverance is not a long race; it is many short races one after another. - Walter Elliot",
    "Great things are not done by impulse, but by a series of small things brought together. - Vincent van Gogh",
    "If you want to make an easy job seem mighty hard, just keep putting off doing it. - Olin Miller",
    "Energy and persistence conquer all things. - Benjamin Franklin",
    "If you can dream it, you can do it. - Walt Disney",
    "The secret of change is to focus all your energy not on fighting the old, but on building the new. - Socrates (attributed)",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "Don't judge each day by the harvest you reap but by the seeds that you plant. - Robert Louis Stevenson",
    "Go as far as you can see; when you get there, you'll be able to see further. - Thomas Carlyle",
    "It always seems impossible until it's done. - Nelson Mandela",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
    "Light tomorrow with today. - Elizabeth Barrett Browning",
    "Well done is better than well said. - Benjamin Franklin",
    "Keep going. No feeling is final. - Rainer Maria Rilke",
    "We become what we think about. - Earl Nightingale",
    "Rise above the storm and you will find the sunshine. - Mario Fernández"
  ],
  jewish: [
    "The world stands on three things: on Torah, on service, and on acts of kindness. - Pirkei Avot 1:2",
    "Who is wise? One who learns from every person. - Pirkei Avot 4:1",
    "Who is strong? One who conquers his inclination. - Pirkei Avot 4:1",
    "Who is rich? One who rejoices in his lot. - Pirkei Avot 4:1",
    "If I am not for myself, who will be for me? And if I am only for myself, what am I? And if not now, when? - Hillel, Pirkei Avot 1:14",
    "Say little and do much. - Pirkei Avot 1:15",
    "According to the effort is the reward. - Pirkei Avot 5:26",
    "In a place where there are no people, strive to be a person. - Pirkei Avot 2:6",
    "It is not your duty to finish the work, but neither are you free to desist from it. - Pirkei Avot 2:16",
    "The more charity, the more peace. - Pirkei Avot 2:7",
    "A good heart is the best of traits. - Pirkei Avot 2:9",
    "Whoever destroys one life, it is as if he destroyed an entire world; and whoever saves one life, it is as if he saved an entire world. - Mishnah Sanhedrin 4:5",
    "Trust in the Lord with all your heart, and lean not on your own understanding. - Proverbs 3:5",
    "Commit your work to the Lord, and your plans will be established. - Proverbs 16:3",
    "A joyful heart makes a cheerful face. - Proverbs 15:13",
    "The Lord is my shepherd; I shall not want. - Psalm 23:1",
    "Teach us to number our days, that we may gain a heart of wisdom. - Psalm 90:12",
    "Light is sown for the righteous, and joy for the upright in heart. - Psalm 97:11",
    "Seek peace and pursue it. - Psalm 34:14",
    "The beginning of wisdom is this: Get wisdom. - Proverbs 4:7",
    "Who is honored? One who honors others. - Pirkei Avot 4:1",
    "One moment of repentance and good deeds in this world is better than the entire life of the world to come. - Avot d'Rabbi Natan",
    "A little light dispels much darkness. - Chabad teaching",
    "As long as the candle is burning, there is time to make repairs. - Rabbi Yisrael Salanter",
    "The highest wisdom is kindness. - Talmud (Berachot)",
    "Judge every person favorably. - Pirkei Avot 1:6",
    "Say to yourself: for me the world was created. - Mishnah Sanhedrin 4:5",
    "In the place where penitents stand, even the wholly righteous cannot stand. - Talmud (Berachot 34b)",
    "Greet every person with a cheerful face. - Pirkei Avot 1:15",
    "Where there is no flour, there is no Torah; where there is no Torah, there is no flour. - Pirkei Avot 3:17",
    "Silence is a fence for wisdom. - Pirkei Avot 3:17",
    "Who is wealthy? One who is satisfied with his portion. - Pirkei Avot 4:1",
    "The day is short, the work is much, the workers are lazy, the reward is great, and the Master is pressing. - Pirkei Avot 2:15",
    "The crown of a good name is superior to them all. - Pirkei Avot 4:13",
    "Do not separate yourself from the community. - Pirkei Avot 2:5",
    "Blessed is the one who trusts in the Lord, whose trust is the Lord. - Jeremiah 17:7",
    "For I know the plans I have for you, declares the Lord. - Jeremiah 29:11",
    "The Lord will guard your going and your coming, from this time forth and forever. - Psalm 121:8",
    "Teach a child according to his way; even when he grows old, he will not turn from it. - Proverbs 22:6",
    "Her ways are ways of pleasantness, and all her paths are peace. - Proverbs 3:17",
    "Trust in the Lord and do good; dwell in the land and cultivate faithfulness. - Psalm 37:3",
    "The righteous shall flourish like a palm tree. - Psalm 92:12",
    "A man's pride shall bring him low; but honor shall uphold the humble in spirit. - Proverbs 29:23",
    "Better is a little with righteousness than great revenues without right. - Proverbs 16:8",
    "The Lord is near to all who call upon Him, to all who call upon Him in truth. - Psalm 145:18",
    "He heals the brokenhearted and binds up their wounds. - Psalm 147:3",
    "From my distress I called upon the Lord; He answered me and set me in a broad place. - Psalm 118:5",
    "Light arises in the darkness for the upright. - Psalm 112:4"
  ],
  mindfulness: [
    "The best way to take care of the future is to take care of the present moment. - Thich Nhat Hanh",
    "Walk as if you are kissing the Earth with your feet. - Thich Nhat Hanh",
    "Feelings come and go like clouds in a windy sky; conscious breathing is my anchor. - Thich Nhat Hanh",
    "You can't stop the waves, but you can learn to surf. - Jon Kabat-Zinn",
    "Wherever you go, there you are. - Jon Kabat-Zinn",
    "Mindfulness is paying attention, on purpose, in the present moment, non-judgmentally. - Jon Kabat-Zinn",
    "Let go of what you think should be happening and be with what is. - Jon Kabat-Zinn",
    "Start where you are. - Pema Chödrön",
    "Nothing ever goes away until it has taught us what we need to know. - Pema Chödrön",
    "You are the sky. Everything else is just the weather. - Pema Chödrön",
    "Mindfulness isn't difficult; we just need to remember to do it. - Sharon Salzberg",
    "The difference between misery and happiness depends on what we do with our attention. - Sharon Salzberg",
    "Kindness is not a luxury; it is essential to our survival. - Sharon Salzberg",
    "You are not your thoughts; you are the awareness behind them. - Eckhart Tolle",
    "Realize deeply that the present moment is all you ever have. - Eckhart Tolle",
    "Whatever the present moment contains, accept it as if you had chosen it. - Eckhart Tolle",
    "Whatever you practice grows stronger. - Shauna Shapiro",
    "Mindfulness is the aware, balanced acceptance of the present experience. - Sylvia Boorstein",
    "Bring your full attention to what is actually here. - Joseph Goldstein",
    "See clearly, let go gently, act wisely. - Joseph Goldstein",
    "Wisdom grows from seeing things as they are. - Joseph Goldstein",
    "Anxiety is excitement without the breath. - Fritz Perls",
    "The boundary to what we can accept is the boundary to our freedom. - Tara Brach",
    "Radical acceptance opens the door to real change. - Tara Brach",
    "Pause. Breathe. Now begin again. - Tara Brach",
    "If you let go a little, you will have a little peace; let go a lot, you will have a lot of peace; let go completely, you will have complete peace. - Ajahn Chah",
    "Why are you so busy? Take a look at your mind. - Ajahn Chah",
    "Make peace, be kind, be gentle. - Ajahn Brahm",
    "Waking up this morning, I smile. Twenty-four brand new hours are before me. - Thich Nhat Hanh",
    "Breathing in, I calm my body. Breathing out, I smile. - Thich Nhat Hanh",
    "Each moment missed is a moment unlived. - Jon Kabat-Zinn",
    "There is more right with you than wrong with you. - Jon Kabat-Zinn",
    "Relax as it is, and relax as you are. - Pema Chödrön",
    "What we resist, persists; what we turn toward can transform. - Tara Brach",
    "The brain is like Velcro for bad experiences but Teflon for good; take in the good. - Rick Hanson",
    "Drop by drop, the bucket fills. - Rick Hanson",
    "Mindfulness means being awake. It means knowing what you are doing. - Jon Kabat-Zinn",
    "Mindfulness is non-judgmental awareness of the present moment. - Bhante Gunaratana",
    "Be mindful of the gap between impulse and action. - Bhante Gunaratana",
    "The heart is like a garden; it can grow compassion or fear. - Jack Kornfield",
    "Lean into the sharp points and fully experience them. - Pema Chödrön",
    "Right now, it's like this. - Ajahn Sumedho",
    "Satipatthana is a way of living fully, not a technique. - Bhikkhu Analayo",
    "To offer no resistance to life is to be in a state of grace. - Eckhart Tolle",
    "Treat yourself with the same kindness you would offer a friend. - Kristin Neff",
    "When you do something, you should do it with your whole body and mind. - Shunryu Suzuki",
    "Sometimes your joy is the source of your smile; sometimes your smile is the source of your joy. - Thich Nhat Hanh",
    "Let your breath be your home. - Tara Brach",
    "Come back to the body; it never lies. - Joseph Goldstein"
  ],
  muslim: [
    "Indeed, with hardship [will be] ease. - Qur'an 94:6",
    "So remember Me; I will remember you. - Qur'an 2:152",
    "Allah does not burden a soul beyond that it can bear. - Qur'an 2:286",
    "And whoever fears Allah - He will make for him a way out. - Qur'an 65:2",
    "And He will provide for him from where he does not expect. - Qur'an 65:3",
    "So be patient. Indeed, the promise of Allah is truth. - Qur'an 30:60",
    "And We have certainly created man and We know what his soul whispers to him. - Qur'an 50:16",
    "And whoever relies upon Allah - then He is sufficient for him. - Qur'an 65:3",
    "And the servants of the Most Merciful are those who walk upon the earth easily. - Qur'an 25:63",
    "Unquestionably, by the remembrance of Allah hearts are assured. - Qur'an 13:28",
    "Do not lose hope, nor be sad. - Qur'an 3:139",
    "Indeed, Allah is with the patient. - Qur'an 2:153",
    "So verily, with the hardship, there is relief. - Qur'an 94:5",
    "And whoever does an atom's weight of good will see it. - Qur'an 99:7",
    "And whoever puts his trust in Allah, then He will suffice him. - Qur'an 65:3",
    "The strong man is not the one who overpowers in wrestling; the strong man is the one who controls himself in anger. - Hadith (Bukhari, Muslim)",
    "Allah does not look at your forms or your wealth, but He looks at your hearts and your deeds. - Hadith (Muslim)",
    "Make things easy and do not make them difficult; give glad tidings and do not repel people. - Hadith (Bukhari, Muslim)",
    "He who does not thank people, does not thank Allah. - Hadith (Tirmidhi)",
    "Tie your camel and trust in Allah. - Hadith (Tirmidhi)",
    "Whoever believes in Allah and the Last Day should speak good or remain silent. - Hadith (Bukhari, Muslim)",
    "The most beloved deeds to Allah are those that are most consistent, even if small. - Hadith (Bukhari, Muslim)",
    "A Muslim is the one from whose tongue and hand the people are safe. - Hadith (Nasa'i)",
    "Be in this world as though you were a stranger or a traveler. - Hadith (Bukhari)",
    "Exchange gifts, you will love one another. - Hadith (Bukhari)",
    "Give charity without delay, for it stands in the way of calamity. - Hadith (Tirmidhi)",
    "The best of people are those that bring most benefit to the rest of mankind. - Hadith (Daraqutni)",
    "The cure for ignorance is to question. - Hadith (Abu Dawud)",
    "Kindness is a mark of faith, and whoever has not kindness has not faith. - Hadith (Tirmidhi)",
    "Richness is not having many possessions; rather, richness is contentment of the soul. - Hadith (Bukhari, Muslim)",
    "If you feel no shame, then do as you wish. - Hadith (Bukhari)",
    "Whoever relieves a believer's distress, Allah will relieve his distress on the Day of Resurrection. - Hadith (Muslim)",
    "The best among you are those who have the best manners and character. - Hadith (Bukhari)",
    "The strong believer is better and more beloved to Allah than the weak believer, while there is good in both. - Hadith (Muslim)",
    "Take advantage of five before five: your youth before your old age, your health before your illness, your wealth before your poverty, your free time before your work, and your life before your death. - Hadith (Hakim)",
    "The world is a prison for the believer and a paradise for the unbeliever. - Hadith (Muslim)",
    "Whoever believes in Allah and the Last Day, let him maintain the ties of kinship. - Hadith (Bukhari, Muslim)",
    "Speak a good word or remain silent. - Hadith (Bukhari, Muslim)",
    "The best of you are those who are best to their families. - Hadith (Tirmidhi)",
    "Exchange greetings of peace; you will love one another. - Hadith (Muslim)",
    "Make wudu' (ablution) thoroughly even in difficulty. - Hadith (Muslim)",
    "Whoever is not grateful for little will not be grateful for much. - Hadith (Ahmad)",
    "Be mindful of Allah, you will find Him before you. - Hadith (Tirmidhi)",
    "Whoever would like his provision increased and his life extended, let him maintain kinship. - Hadith (Bukhari, Muslim)",
    "Keep your tongue moist with the remembrance of Allah. - Hadith (Tirmidhi)",
    "Verily, Allah loves those who are constantly repentant and loves those who purify themselves. - Qur'an 2:222",
    "And He found you lost and guided [you]. - Qur'an 93:7",
    "So be patient with gracious patience. - Qur'an 70:5",
    "Indeed, prayer prohibits immorality and wrongdoing. - Qur'an 29:45"
  ],
  philosophical: [
    "The unexamined life is not worth living. - Socrates",
    "The only true wisdom is in knowing you know nothing. - Socrates",
    "The beginning is the most important part of the work. - Plato",
    "Courage is knowing what not to fear. - Plato",
    "Well begun is half done. - Aristotle",
    "The energy of the mind is the essence of life. - Aristotle",
    "Nature does nothing in vain. - Aristotle",
    "The sun is new each day. - Heraclitus",
    "Character is destiny. - Heraclitus",
    "There is nothing permanent except change. - Heraclitus",
    "I think, therefore I am. - René Descartes",
    "Divide each difficulty into as many parts as is feasible and necessary to resolve it. - René Descartes",
    "He who has a why to live can bear almost any how. - Friedrich Nietzsche",
    "That which does not kill us makes us stronger. - Friedrich Nietzsche",
    "Life can only be understood backwards; but it must be lived forwards. - Søren Kierkegaard",
    "In the midst of winter, I found there was, within me, an invincible summer. - Albert Camus",
    "All things excellent are as difficult as they are rare. - Baruch Spinoza",
    "A wise man proportions his belief to the evidence. - David Hume",
    "The actions of men are the best interpreters of their thoughts. - John Locke",
    "Happiness is not an ideal of reason but of imagination. - Immanuel Kant",
    "Two things fill the mind with ever new and increasing admiration and awe: the starry heavens above me and the moral law within me. - Immanuel Kant",
    "The greatest thing in the world is to know how to belong to oneself. - Michel de Montaigne",
    "Knowing others is intelligence; knowing yourself is true wisdom. - Lao Tzu",
    "Mastering others is strength; mastering yourself is true power. - Lao Tzu",
    "Our greatest glory is not in never falling, but in rising every time we fall. - Confucius",
    "The superior man is modest in his speech but exceeds in his actions. - Confucius",
    "We do not see things as they are, we see them as we are. - Anaïs Nin",
    "The art of being wise is the art of knowing what to overlook. - William James",
    "Education is the kindling of a flame, not the filling of a vessel. - Plutarch",
    "Happiness is when what you think, what you say, and what you do are in harmony. - Mahatma Gandhi",
    "The only journey is the one within. - Rainer Maria Rilke",
    "The good life is one inspired by love and guided by knowledge. - Bertrand Russell",
    "The only real voyage of discovery consists not in seeking new landscapes, but in having new eyes. - Marcel Proust",
    "The limits of my language mean the limits of my world. - Ludwig Wittgenstein",
    "We are what we pretend to be, so we must be careful what we pretend to be. - Kurt Vonnegut",
    "The more one judges, the less one loves. - Honoré de Balzac",
    "To be is to be perceived. - George Berkeley",
    "The greatest wealth is to live content with little. - Plato",
    "The important thing is not to stop questioning. - Albert Einstein",
    "We must cultivate our garden. - Voltaire",
    "Act only according to that maxim whereby you can at the same time will that it should become a universal law. - Immanuel Kant",
    "The whole is more than the sum of its parts. - Aristotle",
    "Whereof one cannot speak, thereof one must be silent. - Ludwig Wittgenstein",
    "The more you know yourself, the more clarity there is. - Jiddu Krishnamurti",
    "Freedom is what you do with what's been done to you. - Jean-Paul Sartre",
    "Man is the measure of all things. - Protagoras",
    "Be a philosopher; but, amid all your philosophy, be still a man. - David Hume",
    "He who knows that enough is enough will always have enough. - Lao Tzu",
    "The roots of education are bitter, but the fruit is sweet. - Aristotle",
    "Time is the wisest counselor of all. - Pericles"
  ],
  stoic: [
    "You have power over your mind, not outside events. Realize this, and you will find strength. - Marcus Aurelius",
    "The impediment to action advances action. What stands in the way becomes the way. - Marcus Aurelius",
    "Waste no more time arguing what a good man should be. Be one. - Marcus Aurelius",
    "If it is not right, do not do it; if it is not true, do not say it. - Marcus Aurelius",
    "The happiness of your life depends upon the quality of your thoughts. - Marcus Aurelius",
    "When you arise in the morning, think of what a precious privilege it is to be alive. - Marcus Aurelius",
    "Dwell on the beauty of life. Watch the stars, and see yourself running with them. - Marcus Aurelius",
    "Do every act of your life as though it were the very last act of your life. - Marcus Aurelius",
    "The best revenge is not to be like your enemy. - Marcus Aurelius",
    "Because a thing seems difficult for you, do not think it impossible for anyone to accomplish. - Marcus Aurelius",
    "Look well within; there is a fountain of goodness that will never cease flowing if you stop digging. - Marcus Aurelius",
    "If someone can prove me wrong and show me my mistake, I will gladly change. - Marcus Aurelius",
    "It's not what happens to you, but how you react to it that matters. - Epictetus",
    "No man is free who is not master of himself. - Epictetus",
    "First say to yourself what you would be; then do what you have to do. - Epictetus",
    "Don't explain your philosophy. Embody it. - Epictetus",
    "Wealth consists not in having great possessions, but in having few wants. - Epictetus",
    "Make the best use of what is in your power, and take the rest as it happens. - Epictetus",
    "Circumstances do not make the man; they reveal him to himself. - Epictetus",
    "If you want to improve, be content to be thought foolish and stupid. - Epictetus",
    "Freedom is the only worthy goal in life; it is won by disregarding things that lie beyond our control. - Epictetus",
    "It is not that we have a short time to live, but that we waste much of it. - Seneca",
    "Begin at once to live, and count each separate day as a separate life. - Seneca",
    "Luck is what happens when preparation meets opportunity. - Seneca",
    "If a man knows not to which port he sails, no wind is favorable. - Seneca",
    "He who is brave is free. - Seneca",
    "Associate with those who will make a better man of you. - Seneca",
    "Difficulties strengthen the mind, as labor does the body. - Seneca",
    "As is a tale, so is life: not how long it is, but how good it is. - Seneca",
    "True happiness is to enjoy the present, without anxious dependence on the future. - Seneca",
    "We suffer more often in imagination than in reality. - Seneca",
    "Hang on to your youthful enthusiasms; you will be able to use them better when you are older. - Seneca",
    "Man is not worried by real problems so much as by his imagined anxieties about real problems. - Epictetus",
    "Be tolerant with others and strict with yourself. - Marcus Aurelius",
    "How ridiculous and how strange to be surprised at anything which happens in life. - Marcus Aurelius",
    "The soul becomes dyed with the color of its thoughts. - Marcus Aurelius",
    "To love only what happens, what was destined. No greater harmony. - Marcus Aurelius",
    "If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it. - Marcus Aurelius",
    "Men are disturbed not by things, but by the views they take of them. - Epictetus",
    "Do not seek for everything to happen as you wish it, but rather wish that everything happens as it actually will. - Epictetus",
    "No great thing is created suddenly. - Epictetus",
    "The chief task in life is simply this: to identify and separate matters so that I can say clearly which are externals not under my control, and which are the choices I actually control. - Epictetus",
    "What progress have I made? I am beginning to be my own friend. - Seneca",
    "He who has great power should use it lightly. - Seneca",
    "Sometimes even to live is an act of courage. - Seneca",
    "A gem cannot be polished without friction, nor a man perfected without trials. - Seneca",
    "Receive without pride, let go without attachment. - Marcus Aurelius",
    "Be like the rock that the waves keep crashing over; it stands unmoved and the raging of the sea falls still around it. - Marcus Aurelius",
    "Remember that very little is needed to make a happy life. - Marcus Aurelius",
    "The more we value things outside our control, the less control we have. - Epictetus",
    "Fate leads the willing and drags the unwilling. - Seneca"
  ],
  success: [
    "Genius is one percent inspiration and ninety-nine percent perspiration. - Thomas Edison",
    "Whether you think you can or you think you can't, you're right. - Henry Ford",
    "You miss one hundred percent of the shots you don't take. - Wayne Gretzky",
    "I have not failed. I've just found ten thousand ways that won't work. - Thomas Edison",
    "The best time to plant a tree was twenty years ago. The second best time is now. - Chinese Proverb",
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "Well done is better than well said. - Benjamin Franklin",
    "It always seems impossible until it's done. - Nelson Mandela",
    "Action is the foundational key to all success. - Pablo Picasso",
    "The secret of getting ahead is getting started. - Mark Twain",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
    "Motivation is what gets you started. Habit is what keeps you going. - Jim Ryun",
    "Discipline is the bridge between goals and accomplishment. - Jim Rohn",
    "If you really want to do something, you'll find a way; if you don't, you'll find an excuse. - Jim Rohn",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "Done is better than perfect. - Sheryl Sandberg",
    "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
    "Don't let what you cannot do interfere with what you can do. - John Wooden",
    "Make each day your masterpiece. - John Wooden",
    "Be quick, but don't hurry. - John Wooden",
    "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
    "Dream big and dare to fail. - Norman Vaughan",
    "A goal without a plan is just a wish. - Antoine de Saint-Exupéry",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "Hard choices, easy life. Easy choices, hard life. - Jerzy Gregorek",
    "The man who moves a mountain begins by carrying away small stones. - Confucius",
    "If I cannot do great things, I can do small things in a great way. - Martin Luther King Jr.",
    "What we fear doing most is usually what we most need to do. - Tim Ferriss",
    "There is nothing so useless as doing efficiently that which should not be done at all. - Peter Drucker",
    "If you want to go fast, go alone. If you want to go far, go together. - African Proverb",
    "Amateurs sit and wait for inspiration; the rest of us just get up and go to work. - Stephen King",
    "Success is liking yourself, liking what you do, and liking how you do it. - Maya Angelou",
    "Energy and persistence conquer all things. - Benjamin Franklin",
    "Small deeds done are better than great deeds planned. - Peter Marshall",
    "Either you run the day, or the day runs you. - Jim Rohn",
    "Don't wish it were easier; wish you were better. - Jim Rohn",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "If opportunity doesn't knock, build a door. - Milton Berle",
    "Fall seven times and stand up eight. - Japanese Proverb",
    "He who is not courageous enough to take risks will accomplish nothing in life. - Muhammad Ali",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "What you do every day matters more than what you do once in a while. - Gretchen Rubin",
    "The future depends on what you do today. - Mahatma Gandhi",
    "The harder I practice, the luckier I get. - Gary Player",
    "Plans are only good intentions unless they immediately degenerate into hard work. - Peter Drucker",
    "Deciding what not to do is as important as deciding what to do. - Steve Jobs",
    "Your time is limited, so don't waste it living someone else's life. - Steve Jobs",
    "Never let the fear of striking out keep you from playing the game. - Babe Ruth"
  ],
  zen: [
    "When walking, walk. When eating, eat. - Zen proverb",
    "Let go or be dragged. - Zen proverb",
    "Chop wood, carry water. - Zen proverb",
    "Before enlightenment, chop wood; carry water. After enlightenment, chop wood; carry water. - Zen saying",
    "The finger pointing at the moon is not the moon. - Zen proverb",
    "Sitting quietly, doing nothing; spring comes and the grass grows by itself. - Zen proverb",
    "Empty your cup. - Zen proverb",
    "The quieter you become, the more you can hear. - Zen proverb",
    "No snowflake ever falls in the wrong place. - Zen proverb",
    "When the mind is clear, the path is easy. - Zen proverb",
    "If you understand, things are just as they are; if you do not understand, things are just as they are. - Zen proverb",
    "Every day is a good day. - Yunmen",
    "Not knowing is most intimate. - Fayan",
    "The Great Way is not difficult for those who have no preferences. - Sengcan",
    "The ten thousand things return to the One; the One returns to the ten thousand things. - Zen proverb",
    "To study the Way is to study the self; to study the self is to forget the self. - Dogen",
    "To forget the self is to be awakened by the myriad things. - Dogen",
    "If you cannot find the truth right where you are, where else do you expect to find it? - Dogen",
    "A flower falls, even though we love it; a weed grows, even though we do not love it. - Dogen",
    "In the beginner's mind there are many possibilities; in the expert's there are few. - Shunryu Suzuki",
    "When you do something, you should burn yourself completely, like a good bonfire. - Shunryu Suzuki",
    "Zen is not some kind of excitement, but concentration on our usual everyday routine. - Shunryu Suzuki",
    "The most important point is to find out what is the most important point. - Shunryu Suzuki",
    "When you reach the top of the mountain, keep climbing. - Zen proverb",
    "Do not seek the truth; only cease to cherish opinions. - Sengcan",
    "When the wind blows, there is movement; when the mind is still, the world rests. - Zen proverb",
    "Move and the way opens. - Zen proverb",
    "Today only, with your whole heart, just this. - Zen proverb",
    "When the mind is nowhere, it is everywhere. - Zen proverb",
    "The practice is the goal. - Zen proverb",
    "Clouds come and go, yet the sky remains. - Zen proverb",
    "Do not seek it without; the treasure is within. - Zen proverb",
    "Silence is the gate to the Way. - Zen proverb",
    "If you want to find, stop seeking. - Zen proverb",
    "Water flows, the moon floats. - Zen proverb",
    "Great doubt, great awakening; little doubt, little awakening; no doubt, no awakening. - Hakuin Ekaku",
    "Not one, not two. - Zen saying",
    "The moon is reflected in the water; the water is not broken. - Zen proverb",
    "When hungry, eat; when tired, sleep. - Zen proverb",
    "The miracle is to walk on earth. - Thich Nhat Hanh",
    "Where you stand, stand firm; where you sit, sit true. - Zen proverb",
    "Don't seek, don't avoid; accept what comes and trust. - Zen proverb",
    "The great path is the one beneath your feet. - Zen proverb",
    "To control your cow, give it a wide pasture. - Zen proverb",
    "Let thoughts come and go; just don't serve them tea. - Zen proverb",
    "Entering the Way is seeing your own nature. - Bodhidharma",
    "Vast emptiness, nothing holy. - Bodhidharma",
    "The ordinary mind is the Way. - Nansen"
  ],
};

// Create a stable numeric seed from a date (yyyy-mm-dd) and category
function seedFrom(date: Date, category: QuoteCategory): number {
  const yyyy = date.getUTCFullYear();
  const mm = date.getUTCMonth() + 1;
  const dd = date.getUTCDate();
  // Compact YYYYMMDD plus a category offset
  const base = yyyy * 10000 + mm * 100 + dd;
  // Simple category hash using char codes (stable across runtimes)
  let catHash = 0;
  for (let i = 0; i < category.length; i++) {
    catHash = (catHash * 31 + category.charCodeAt(i)) >>> 0;
  }
  return (base ^ catHash) >>> 0;
}

// Deterministically pick an index for a given category on a given date
export function getDeterministicIndex(category: QuoteCategory, date: Date): number {
  const list = quoteLibrary[category] || [];
  const n = list.length;
  if (n === 0) return -1;
  const s = seedFrom(date, category);
  // Mulberry32-like bit mixing for decent distribution
  let t = (s + 0x6D2B79F5) >>> 0;
  t = Math.imul(t ^ (t >>> 15), t | 1);
  t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
  const mixed = ((t ^ (t >>> 14)) >>> 0) / 4294967296; // 0..1
  return Math.floor(mixed * n);
}

// Deterministically select a quote; returns null if category has no entries
export function getDeterministicQuote(category: QuoteCategory, date: Date): string | null {
  const idx = getDeterministicIndex(category, date);
  if (idx < 0) return null;
  return quoteLibrary[category][idx] || null;
}

// Convenience: get quote using ISO date string (yyyy-mm-dd), UTC by default
export function getDeterministicQuoteForISODate(category: QuoteCategory, isoDate: string): string | null {
  // Parse in UTC noon to avoid DST edge issues
  const d = new Date(`${isoDate}T12:00:00Z`);
  if (isNaN(d.getTime())) return null;
  return getDeterministicQuote(category, d);
}


