-- Storage bucket configuration for DayStart audio files
-- Private bucket with signed URL access only

-- Create the storage bucket (run this via Supabase Dashboard or CLI)
-- This file documents the configuration needed

-- Bucket: daystart-audio
-- - Private: true (no public access)
-- - File size limit: 50MB (generous for 3-5 minute audio files)
-- - Allowed MIME types: audio/mpeg, audio/mp4, audio/wav
-- - Path structure: {user_id}/{date}/{job_id}.{ext}

-- Storage policies for the daystart-audio bucket

-- Policy: Service role can upload/manage all files
CREATE POLICY "Service role can manage audio files" ON storage.objects
  FOR ALL TO service_role
  USING (bucket_id = 'daystart-audio');

-- Policy: Users can access their own audio files via signed URLs only
-- (This is handled by the signed URL generation, no direct object access)

-- Policy: Authenticated users can read their own files
CREATE POLICY "Users can read own audio files" ON storage.objects
  FOR SELECT TO authenticated
  USING (
    bucket_id = 'daystart-audio' AND
    (storage.foldername(name))[1] = auth.jwt()->>'user_id'
  );

-- Policy: Anonymous users cannot directly access files
-- (Access only via signed URLs generated by Edge Functions)

-- File naming convention:
-- {user_id}/{local_date}/{job_id}.mp3
-- Example: anonymous_abc123/2025-08-11/550e8400-e29b-41d4-a716-446655440000.mp3

-- Clean up old files (cron job)
-- Files older than 30 days will be removed by background process

-- Storage bucket RLS is automatically enabled
-- File access is controlled through signed URLs with 30-minute expiry